"""add exact dry run approvals

Revision ID: 17c1649fa1ce
Revises: 4ed259e88c60
Create Date: 2026-10-04 23:52:00.922190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17c1649fa1ce'
down_revision: Union[str, Sequence[str], None] = '4ed259e88c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dry_run_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('source_schema_id', sa.Uuid(), nullable=False),
    sa.Column('target_schema_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('bundle_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('bundle_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_revision', sa.Integer(), nullable=False),
    sa.Column('rule_list_version', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('approved', 'rejected')", name=op.f('ck_approvals_valid_decision')),
    sa.CheckConstraint('target_revision >= 0', name=op.f('ck_approvals_nonnegative_target_revision')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_snapshots.id'], name=op.f('fk_approvals_dataset_id_dataset_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dry_run_id'], ['dry_runs.id'], name=op.f('fk_approvals_dry_run_id_dry_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plan_versions.id'], name=op.f('fk_approvals_plan_id_migration_plan_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['migration_projects.id'], name=op.f('fk_approvals_project_id_migration_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_schema_id'], ['schema_snapshots.id'], name=op.f('fk_approvals_source_schema_id_schema_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_schema_id'], ['schema_snapshots.id'], name=op.f('fk_approvals_target_schema_id_schema_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals')),
    sa.UniqueConstraint('dry_run_id', name='uq_approval_dry_run'),
    sa.UniqueConstraint('project_id', 'bundle_fingerprint', name='uq_approval_bundle_fingerprint')
    )
    op.add_column('migration_projects', sa.Column('target_revision', sa.Integer(), server_default='0', nullable=False))
    op.create_check_constraint(
        'ck_migration_projects_nonnegative_target_revision',
        'migration_projects',
        'target_revision >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_migration_projects_nonnegative_target_revision',
        'migration_projects',
        type_='check',
    )
    op.drop_column('migration_projects', 'target_revision')
    op.drop_table('approvals')
    # ### end Alembic commands ###
