"""add migration plan versions

Revision ID: 264912339a6c
Revises: 2dc6518a14d2
Create Date: 2026-10-04 19:24:14.145062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '264912339a6c'
down_revision: Union[str, Sequence[str], None] = '2dc6518a14d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_plan_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('previous_plan_id', sa.Uuid(), nullable=True),
    sa.Column('source_schema_version_id', sa.Uuid(), nullable=False),
    sa.Column('target_schema_version_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_version_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('plan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_list_version', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'valid', 'invalid')", name=op.f('ck_migration_plan_versions_valid_status')),
    sa.CheckConstraint('version > 0', name=op.f('ck_migration_plan_versions_positive_version')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_snapshots.id'], name=op.f('fk_migration_plan_versions_dataset_version_id_dataset_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_plan_id'], ['migration_plan_versions.id'], name=op.f('fk_migration_plan_versions_previous_plan_id_migration_plan_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['migration_projects.id'], name=op.f('fk_migration_plan_versions_project_id_migration_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_schema_version_id'], ['schema_snapshots.id'], name=op.f('fk_migration_plan_versions_source_schema_version_id_schema_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_schema_version_id'], ['schema_snapshots.id'], name=op.f('fk_migration_plan_versions_target_schema_version_id_schema_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_plan_versions')),
    sa.UniqueConstraint('project_id', 'plan_hash', name='uq_migration_plan_hash'),
    sa.UniqueConstraint('project_id', 'version', name='uq_migration_plan_version')
    )
    op.create_index('ix_migration_plan_project_status', 'migration_plan_versions', ['project_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_migration_plan_project_status', table_name='migration_plan_versions')
    op.drop_table('migration_plan_versions')
    # ### end Alembic commands ###
