"""create phase one tables

Revision ID: 2dc6518a14d2
Revises: 
Create Date: 2026-10-04 17:48:06.939707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dc6518a14d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('response_status IS NULL OR (response_status >= 100 AND response_status <= 599)', name=op.f('ck_idempotency_records_valid_response_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('actor_id', 'scope', 'idempotency_key', name='uq_idempotency_actor_scope_key')
    )
    op.create_table('migration_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('target_namespace', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'completed', 'archived')", name=op.f('ck_migration_projects_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_projects'))
    )
    op.create_index(op.f('ix_migration_projects_owner_id'), 'migration_projects', ['owner_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['migration_projects.id'], name=op.f('fk_audit_events_project_id_migration_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_event_project_created', 'audit_events', ['project_id', 'created_at'], unique=False)
    op.create_table('schema_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('previous_schema_id', sa.Uuid(), nullable=True),
    sa.Column('schema_role', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("schema_role IN ('source', 'target')", name=op.f('ck_schema_snapshots_valid_schema_role')),
    sa.CheckConstraint('version > 0', name=op.f('ck_schema_snapshots_positive_version')),
    sa.ForeignKeyConstraint(['previous_schema_id'], ['schema_snapshots.id'], name=op.f('fk_schema_snapshots_previous_schema_id_schema_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['migration_projects.id'], name=op.f('fk_schema_snapshots_project_id_migration_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_snapshots')),
    sa.UniqueConstraint('project_id', 'schema_role', 'schema_hash', name='uq_schema_snapshot_hash'),
    sa.UniqueConstraint('project_id', 'schema_role', 'version', name='uq_schema_snapshot_version')
    )
    op.create_index('ix_schema_snapshot_project_role', 'schema_snapshots', ['project_id', 'schema_role'], unique=False)
    op.create_table('dataset_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_schema_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_object_key', sa.String(length=512), nullable=False),
    sa.Column('original_checksum', sa.String(length=64), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('upload_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='uploading', nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploading', 'processing', 'ready', 'failed')", name=op.f('ck_dataset_snapshots_valid_status')),
    sa.CheckConstraint('record_count >= 0', name=op.f('ck_dataset_snapshots_nonnegative_record_count')),
    sa.CheckConstraint('upload_size_bytes >= 0', name=op.f('ck_dataset_snapshots_nonnegative_upload_size')),
    sa.CheckConstraint('version > 0', name=op.f('ck_dataset_snapshots_positive_version')),
    sa.ForeignKeyConstraint(['project_id'], ['migration_projects.id'], name=op.f('fk_dataset_snapshots_project_id_migration_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_schema_snapshot_id'], ['schema_snapshots.id'], name=op.f('fk_dataset_snapshots_source_schema_snapshot_id_schema_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_snapshots')),
    sa.UniqueConstraint('project_id', 'version', name='uq_dataset_snapshot_version')
    )
    op.create_table('dataset_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('field_statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_hash', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name=op.f('ck_dataset_profiles_valid_status')),
    sa.CheckConstraint('profile_version > 0', name=op.f('ck_dataset_profiles_positive_profile_version')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_snapshots.id'], name=op.f('fk_dataset_profiles_dataset_id_dataset_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_profiles')),
    sa.UniqueConstraint('dataset_id', 'profile_version', name='uq_dataset_profile_version')
    )
    op.create_table('source_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.String(length=128), nullable=False),
    sa.Column('row_ordinal', sa.Integer(), nullable=False),
    sa.Column('original_record', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canonical_record', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('schema_valid', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('row_ordinal >= 0', name=op.f('ck_source_records_nonnegative_row_ordinal')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_snapshots.id'], name=op.f('fk_source_records_dataset_id_dataset_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_records')),
    sa.UniqueConstraint('dataset_id', 'row_ordinal', name='uq_source_record_ordinal'),
    sa.UniqueConstraint('dataset_id', 'source_record_id', name='uq_source_record_identity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_records')
    op.drop_table('dataset_profiles')
    op.drop_table('dataset_snapshots')
    op.drop_index('ix_schema_snapshot_project_role', table_name='schema_snapshots')
    op.drop_table('schema_snapshots')
    op.drop_index('ix_audit_event_project_created', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_migration_projects_owner_id'), table_name='migration_projects')
    op.drop_table('migration_projects')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
