"""add migration execution lifecycle

Revision ID: 49fc35f15da8
Revises: 5e0892660556
Create Date: 2026-10-05 00:14:27.048238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49fc35f15da8'
down_revision: Union[str, Sequence[str], None] = '5e0892660556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('migration_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=False),
    sa.Column('dry_run_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('target_revision_before', sa.Integer(), nullable=False),
    sa.Column('target_revision_after', sa.Integer(), nullable=False),
    sa.Column('reconciliation', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'reconciliation_failed', 'rolled_back', 'rollback_conflict', 'failed')", name=op.f('ck_migration_runs_valid_status')),
    sa.CheckConstraint('source_count = accepted_count + rejected_count', name=op.f('ck_migration_runs_balanced_counts')),
    sa.CheckConstraint('source_count >= 0 AND accepted_count >= 0 AND rejected_count >= 0 AND inserted_count >= 0', name=op.f('ck_migration_runs_nonnegative_counts')),
    sa.CheckConstraint('target_revision_before >= 0 AND target_revision_after >= 0', name=op.f('ck_migration_runs_nonnegative_target_revisions')),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], name=op.f('fk_migration_runs_approval_id_approvals'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dry_run_id'], ['dry_runs.id'], name=op.f('fk_migration_runs_dry_run_id_dry_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plan_versions.id'], name=op.f('fk_migration_runs_plan_id_migration_plan_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['migration_projects.id'], name=op.f('fk_migration_runs_project_id_migration_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_runs')),
    sa.UniqueConstraint('approval_id', name='uq_migration_run_approval')
    )
    op.create_index('ix_migration_run_project_status', 'migration_runs', ['project_id', 'status'], unique=False)
    op.create_table('migration_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('migration_run_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('execute', 'retry', 'reconcile', 'rollback')", name=op.f('ck_migration_attempts_valid_action')),
    sa.CheckConstraint("status IN ('succeeded', 'failed')", name=op.f('ck_migration_attempts_valid_status')),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], name=op.f('fk_migration_attempts_migration_run_id_migration_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_attempts'))
    )
    op.create_index('ix_migration_attempt_run', 'migration_attempts', ['migration_run_id', 'created_at'], unique=False)
    op.create_table('write_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('migration_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_record_id', sa.Uuid(), nullable=False),
    sa.Column('target_record_id', sa.Uuid(), nullable=True),
    sa.Column('business_key_hash', sa.String(length=64), nullable=False),
    sa.Column('expected_record_hash', sa.String(length=64), nullable=False),
    sa.Column('target_revision', sa.Integer(), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['migration_run_id'], ['migration_runs.id'], name=op.f('fk_write_ledger_migration_run_id_migration_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], name=op.f('fk_write_ledger_source_record_id_source_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_record_id'], ['target_records.id'], name=op.f('fk_write_ledger_target_record_id_target_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_write_ledger')),
    sa.UniqueConstraint('migration_run_id', 'business_key_hash', name='uq_write_ledger_business_key'),
    sa.UniqueConstraint('migration_run_id', 'source_record_id', name='uq_write_ledger_source')
    )
    op.create_index('ix_write_ledger_run', 'write_ledger', ['migration_run_id'], unique=False)
    op.add_column('target_records', sa.Column('migration_run_id', sa.Uuid(), nullable=True))
    op.add_column('target_records', sa.Column('source_record_id', sa.Uuid(), nullable=True))
    op.add_column('target_records', sa.Column('target_revision', sa.Integer(), nullable=True))
    op.create_index('ix_target_record_migration_run', 'target_records', ['migration_run_id'], unique=False)
    op.create_foreign_key(op.f('fk_target_records_migration_run_id_migration_runs'), 'target_records', 'migration_runs', ['migration_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_target_records_source_record_id_source_records'), 'target_records', 'source_records', ['source_record_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_target_records_source_record_id_source_records'), 'target_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_target_records_migration_run_id_migration_runs'), 'target_records', type_='foreignkey')
    op.drop_index('ix_target_record_migration_run', table_name='target_records')
    op.drop_column('target_records', 'target_revision')
    op.drop_column('target_records', 'source_record_id')
    op.drop_column('target_records', 'migration_run_id')
    op.drop_index('ix_write_ledger_run', table_name='write_ledger')
    op.drop_table('write_ledger')
    op.drop_index('ix_migration_attempt_run', table_name='migration_attempts')
    op.drop_table('migration_attempts')
    op.drop_index('ix_migration_run_project_status', table_name='migration_runs')
    op.drop_table('migration_runs')
    # ### end Alembic commands ###
