"""add agent runs and questions

Revision ID: 4ab8775fc2e9
Revises: 8f31c2d70a44
Create Date: 2026-10-04 23:28:32.107488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ab8775fc2e9'
down_revision: Union[str, Sequence[str], None] = '8f31c2d70a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('source_schema_id', sa.Uuid(), nullable=False),
    sa.Column('target_schema_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='running', nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('rule_list_version', sa.String(length=32), nullable=False),
    sa.Column('revision_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'needs_clarification', 'ready_for_review', 'invalid', 'failed')", name=op.f('ck_agent_runs_valid_status')),
    sa.CheckConstraint('revision_count >= 0', name=op.f('ck_agent_runs_nonnegative_revision_count')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_snapshots.id'], name=op.f('fk_agent_runs_dataset_id_dataset_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['migration_plan_versions.id'], name=op.f('fk_agent_runs_plan_id_migration_plan_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['migration_projects.id'], name=op.f('fk_agent_runs_project_id_migration_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_schema_id'], ['schema_snapshots.id'], name=op.f('fk_agent_runs_source_schema_id_schema_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_schema_id'], ['schema_snapshots.id'], name=op.f('fk_agent_runs_target_schema_id_schema_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index('ix_agent_run_project_status', 'agent_runs', ['project_id', 'status'], unique=False)
    op.create_table('agent_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('affected_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('answer', sa.String(length=2000), nullable=True),
    sa.Column('answered_by', sa.String(length=128), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('question_number > 0', name=op.f('ck_agent_questions_positive_question_number')),
    sa.CheckConstraint('revision_number > 0', name=op.f('ck_agent_questions_positive_revision_number')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_agent_questions_agent_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_questions')),
    sa.UniqueConstraint('agent_run_id', 'revision_number', 'question_number', name='uq_agent_question_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_questions')
    op.drop_index('ix_agent_run_project_status', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
