"""add agent evidence and limits

Revision ID: 4ed259e88c60
Revises: 4ab8775fc2e9
Create Date: 2026-10-04 23:37:23.914926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ed259e88c60'
down_revision: Union[str, Sequence[str], None] = '4ab8775fc2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('tool_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('agent_runs', sa.Column('transcript_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('agent_runs', sa.Column('failure_reason', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'failure_reason')
    op.drop_column('agent_runs', 'transcript_metadata')
    op.drop_column('agent_runs', 'tool_evidence')
    # ### end Alembic commands ###
