"""pin dry run execution versions

Revision ID: 5e0892660556
Revises: 17c1649fa1ce
Create Date: 2026-10-04 23:53:16.512999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0892660556'
down_revision: Union[str, Sequence[str], None] = '17c1649fa1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dry_runs', sa.Column('rule_list_version', sa.String(length=32), server_default='1.0', nullable=False))
    op.add_column('dry_runs', sa.Column('engine_version', sa.String(length=32), server_default='1.0', nullable=False))
    op.add_column('dry_runs', sa.Column('target_revision', sa.Integer(), server_default='0', nullable=False))
    op.create_check_constraint(
        'ck_dry_runs_nonnegative_target_revision',
        'dry_runs',
        'target_revision >= 0',
    )
    op.alter_column('dry_runs', 'rule_list_version', server_default=None)
    op.alter_column('dry_runs', 'engine_version', server_default=None)
    op.alter_column('dry_runs', 'target_revision', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_dry_runs_nonnegative_target_revision',
        'dry_runs',
        type_='check',
    )
    op.drop_column('dry_runs', 'target_revision')
    op.drop_column('dry_runs', 'engine_version')
    op.drop_column('dry_runs', 'rule_list_version')
    # ### end Alembic commands ###
